### PR TITLE
Convert acceptance tests to a test project

### PR DESCRIPTION
**Pull request by Rob-Hague**
image

There is currently 1 test failing: fix44/InternationalCharacters.def. The ruby script has a (naughty or nice?) trick with `force_encoding("ASCII-8BIT")` which means that the encoded é is correctly UTF-8 and the rest of the message is the same in UTF-8 as in Latin1, so it just works. This implementation using C# strings (which are UTF-16) has so far no special handling for encoded fields.

I also did not implement the ReflectorServer (eCONNECT), as it is not currently used.

### CODE REVIEW

**Comment by Rob-Hague** [comment]
Actually, I realise that the `Reflector` could just use `Encoding.UTF8` instead of `Encoding.Latin1` and that side of it would be fixed, but because `Reflector.Expect` uses `QuickFix.Parser` which itself has no handling of encoded fields, the test will still fail.

But then given that `QuickFix.Parser` is part of the product, it is probably quite reasonable that the test fails?

**Comment by gbirchmeier** [comment]
I'm still going through it, but this is amazing.  I didn't realize Nunit was even capable of running tests in this way.  Thank you so much!

I'm figuring out what should be needed as far as the ending test.  I'll probably merging this PR after I figure that out.

**Comment by Rob-Hague** [comment]
Sure. Feel free to iterate on it, and happy to help where I can

**Comment by gbirchmeier** [comment]
I pushed a bunch of modest updates.

* Gave the FIX* test cases a differentiating name, each suite has files of the same names
* Made AT use a copy of the parser class instead of the QF one
* Added a 100ms sleep that fixed some instabilities (Ruby actually had this)
* Fixed the InternationalCharacters test (thanks for your comments above, very helpful)
* Made the whole project use nullable

How's it look?  If it looks good to you, I'll merge it.

**Comment by Rob-Hague** [comment]
Looks good to me!

The test still passes with QuickFix.Parser, and ReflectorParser looks functionally the same. Is it intended to keep different versions?

**Comment by gbirchmeier** [comment]
Yeah, I thought it best that the AT own it's own parser, so that one piece can change without affecting the other.  (I actually thought I'd need to change the AT parser for the InternationalChar test, but that didn't turn out to be true.)

Can you take a minute and sign this?
https://cla-assistant.io/connamara/quickfixn?pullRequest=811
(An automated process is supposed to give you this link, but it failed.  I've got to figure that out.)

**Comment by Rob-Hague** [comment]
Done

**Pull request merged**
