### PR TITLE
Proper handling of length defined data fields in FIX messages

### PR DESCRIPTION
**Pull request by larsope**
- Added ExctractDataField method that is called when the parser comes across a FIX data field that has a defined length given by a previous tag.
- Added a unit test to DataDictionaryTests to verify that a message is
read correctly

### CODE REVIEW

**Comment by petre247** [comment]
This pull request is intended to directly address the handling of the XML non-FIX payload message defined by the CME. 
[https://www.cmegroup.com/confluence/display/EPICSANDBOX/Drop+Copy+4.0#DropCopy4.0-EncapsulatedXMLNon-Fix(tag35-MsgType=n)Message](https://www.cmegroup.com/confluence/display/EPICSANDBOX/Drop+Copy+4.0#DropCopy4.0-EncapsulatedXMLNon-Fix(tag35-MsgType=n)Message)

This issue was addressed in the C++ version of QuickFIX in the extractField method of the message class as well.

**Comment by petre247** [comment]
This fix can be linked to issue #301 as a solution

**Comment by gbirchmeier** [comment]
@larsope  Looks like most of this one was ported over to your #782 (which I rebased into #832).

Can I close this?

Furthermore, it looks like I can probably close #301 also.  Do you agree?

**Comment by gbirchmeier** [comment]
I'm closing this, per previous comment.  If I'm mistaken, please let me know.

**Pull request closed without merging**
