### PR TITLE
Add support for NET Standard 2.0

### PR DESCRIPTION
**Pull request by jhickson**
This uses cross-targeting projects to build .NET Framework 4.5.2 and .NET Standard 2.0 versions of the QuickFix.dll assembly, addressing #408. The test and example projects have been similarly updated to build .NET Framework 4.5.2 and .NET Core 2.0. In addition the various test, build and packaging scripts have been changed to run both platforms.

Note:
- I realise there is another PR addressing this (#447) but:
   - the contributor seems to have gone quiet on targeting NET Standard 2.0 instead of 1.6;
   - the PR appears to pull in changes that aren't directly related to supporting NET Standard, e.g. the addition of a console log;
- I chose .NET Framework 4.5.2 because that was the target framework in the original projects but it seems it will also build on version 4.5 - I'm happy to change to that version if desired;
- The only functionality that required disabling for NET Standard 2.0 was `HttpServer`. This is because `System.Web.UI` is not supported outside of .NET Framework:
   - otherwise no changes to the code were required except I did clean up a few warnings I was getting about comments;
- This all means that Visual Studio 2017 or higher is required to open the solution, but there's no way round that unless multiple project versions are to be maintained.
- I note that there is a NuGet package available (https://www.nuget.org/packages/QuickFix.Net/) but could find anything relating to packaging or deploying the NuGet packages in this repo.

### CODE REVIEW

**Comment by jhickson** [comment]
With regard to `HttpServer` - I'm not sure what the way forward is here for it to be supported for .NET Core. It seems `System.Web.UI` won't be ported. ASP.NET uses Razor templates, but I'm not sure how those can be used outside ASP.NET - the standard answer seems to be to use [RazorEngine](https://github.com/Antaris/RazorEngine) but that's .NET Framework only.

**Comment by jhickson** [comment]
There's an [AppVeyor](https://ci.appveyor.com/project/jhickson/quickfixn) build here.

**Comment by jhickson** [comment]
Hi,

I've just fixed the conflicts owing to the recent version bump to 1.8.0 on master.

Now 1.8.0 is out, is there any chance somebody could look at this PR?

**Comment by wklm** [comment]
Thanks a lot @jhickson, I was waiting for net core support for a long time. Awesome job!

**Comment by jhickson** [comment]
Hi @cbusbey, you seem to be one of the principal maintainers of this project. I was wondering if you knew if anybody would have a chance to look at this PR soon? It seems to have generated some interest, and though we can publish a package internally it would be nice to have Net Standard 2.0 support officially supported.

**Comment by jhickson** [comment]
@kkozel Thank you!

**Comment by varevac** [comment]
Is it available now for .NET Core 2.1 ???

**Pull request merged**
