### PR TITLE
Issue 363: fixes for dyamic session functionality

### PR DESCRIPTION
**Pull request by martinadams**
UT code also updated to test fixes.
A couple of the (dynamic session) methods in ThreadedSocketAcceptor.cs moved to the correct code #region.

### CODE REVIEW

**Comment by martinadams** [comment]
Finally passing UT under AppVeyor, which was throwing up some issues not encountered when running UT on development machine. One of these was an ObjectDisposedException being explicitly thrown by FileLog class when an initiator session was being dynamically removed, which happened because the initiator session thread could keep running (and logging) for a bit after session removal, depending on timing. The initiator session removal code has been updated to Join() the session thread before disposing the Session object, so this should help, but the threading structure could perhaps do with a more substantial review at some point (though I've gone about this before!). Also, maybe the FileLog class code should be changed so that it just does nothing if an attempt is made to log after disposal has happened(?)

**Comment by cbusbey** [comment]
Hi @martinadams, would you mind taking another look at this one, looks like we have conflicts.  Thanks!

**Comment by martinadams** [comment]
Hi Chris

 

The conflict is down to NEXT_VERSION.md, which, as had been discussed on previous occasions, is going to be a frequent source of conflict, as pretty much every pull request,  or QF/n release, will include an update to it.

 

I've endeavoured to update the martinadams/quickfixn repo to the current connamara master, but the merge conflict is still being reported. Furthermore,  the relevant new commit (1c9d255) on the pull request is showing deltas against connamara master as was when I branched, rather than connamara master as is now. 

 

I suspect these two things to have the same root cause, but this is where my knowledge of git (and github) runs out (and yes, I've tried searching online for further inspiration). Any advice as how to proceed would be welcome.

**Comment by cbusbey** [comment]
I see.  Well I think going forward we'd prefer contributors to not change any of the version file changes.  Can you please revert that part of your pr so we can accept the rest?

**Comment by martinadams** [comment]
I've reverted that change, and the merge conflict has resolved.

 

Suggested addition to NEXT_VERSION.md is:

 

* (patch) #363 - fixes to new dynamic session functionality (martinadams)

**Comment by cbusbey** [comment]
:beers:

**Pull request merged**
