### PR TITLE
Adding new session settings for ignoring proxy.

### PR DESCRIPTION
**Pull request by ABSJ415**
Adding settings for ignoring proxy. As in some cases using proxy by default can prevent from making connection.

### CODE REVIEW

**Comment by VAllens** [comment]
Good idea, when to merge it?

**Comment by ABSJ415** [comment]
> Good idea, when to merge it?

ASAP :) In our company we need this badly, so right now we are using my fork as temporary measure...

**Comment by VAllens** [comment]
> > Good idea, when to merge it?
> 
> ASAP :) In our company we need this badly, so right now we are using my fork as temporary measure...

Yes, me too... :)

**Comment by VAllens** [comment]
It's been a long time since the team for this project has reviewed PR for it.

**Comment by oniony** [comment]
Any chance this could be merged? I've having to manually set the `http_proxy` environment variable to work around this problem.

**Comment by gbirchmeier** [comment]
Hi all.  The code seems simple enough, but I don't quite understand the use case.  (Sorry, I don't do Windows networking stuff much.)

1) Is this still relevant now that the project is on .NET 6?

2) Is this just telling the MS net library to ignore the configured proxy server and connect directly?

**Comment by ABSJ415** [comment]
1. Yes it is still relevant
2. Yes, it is just telling .net library to ignore the configured proxy server and connect directly.

The use case is to by-pass proxy.

In our case we have on servers set proxy for internet access for security reasons.
But to connect to the server, we need a direct connection, as the proxy prohibits connection that we need to make.

**Comment by gbirchmeier** [comment]
Thanks for the fix, sorry it took so long!

**Comment by gbirchmeier** [comment]
Hi all-- @ABSJ415 @VAllens @oniony @dckorben @abvs372

Since you all have experience with windows proxy configs, can you take a look at PR #742?  This PR fixes an apparent bug when used with Squid proxy, but I want some more eyes on it to make sure it doesn't break anything with regular non-squid proxies.

Thanks!

**Comment by VAllens** [comment]
> Hi all-- @ABSJ415 @VAllens @oniony @dckorben @abvs372
> 
> Since you all have experience with windows proxy configs, can you take a look at PR #742? This PR fixes an apparent bug when used with Squid proxy, but I want some more eyes on it to make sure it doesn't break anything with regular non-squid proxies.
> 
> Thanks!

Ok, let's take a look together.

**Comment by IanLeeClaxton** [comment]
My PR will also enable you to override (disable) the system proxy via .NET config file so not sure this setting is needed but I guess it doesn't hurt to have a hard config for this considering the changes to configuration with dotnet core

**Comment by IanLeeClaxton** [comment]
More info: https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient#http-proxy

**Comment by IanLeeClaxton** [comment]
Probably the correct way to resolve this issue is by using a proxy bypass which can include wildcards for subdomains etc..

**Pull request merged**
