### PR TITLE
Support netstandard21

### PR DESCRIPTION
**Pull request by ThiagoT1**
This PR intends to pave the way for unblocking, low allocation and ValueTask based API's.

The idea is to preserve compatibility to the max extent possibible, while using dependency injection otherwise.

### CODE REVIEW

**Comment by ThiagoT1** [comment]
I need help with appveyor.

**Comment by ThiagoT1** [comment]
@gbirchmeier , would you kindly take a look at this?

**Comment by gbirchmeier** [comment]
Eventually.  I apologize, I'm juggling 3 clients right now and don't have much time for open source at the moment.

**Comment by gbirchmeier** [comment]
Forgive me for asking, but what exactly does this give us?  There's no actual code change here.

It creates a build for .Net Core 3.1, sure, but... isn't the existing Core 2.1 build compatible with post-2.1 projects?

I'm not saying we'll never move up to 3.1.  I just don't see a compelling reason right *now*.  I'd prefer to keep the number of builds down, just for simplicity of maintenance.  (I'm already considering dropping Framework 4.6.1.)

**Comment by gbirchmeier** [comment]
Closing this until a compelling case is made for the upgrade.

**Pull request closed without merging**
