### PR TITLE
Improve dict parsing

### LINKED ISSUE #727: Slow parsing of updated dictionary
I re-generated quickfix dictionary for FIX 5.0 SP2 based on the EP269 specs: https://gist.github.com/sylr/ec83c353902a82b935eec631a010de42

This works well with `quickfix-go` but when I try to use it with `quickfixn` ~~it seems to enter an infinite loop~~ it takes forever.

```c#
var datadict = new QuickFix.DataDictionary.DataDictionary("/Users/sylvain/.fix/FIX50SP2EP269.xml");
```

### PR DESCRIPTION
**Pull request by sylr**
Fixes #727.

### CODE REVIEW

**Comment by gbirchmeier** [comment]
Thanks!  I'll make some time to check this out.

**Comment by VAllens** [comment]
I want to be based on `.NET6.0` completely refactor this project

**Comment by sylr** [comment]
@gbirchmeier any change to get this merged soon ?

**Comment by gbirchmeier** [comment]
@sylr So the root cause of #727 was the slow lookup of components that this PR fixes?

**Comment by sylr** [comment]
Absolutely.

**Pull request merged**
