### PR TITLE
Migration to .NET Standard

### LINKED ISSUE #408: .NET Core support
.NET Core was recently released and it is an exciting new open source cross-platform development from Microsoft in the .NET landscape.  It would be great to have QuickFIX/n for .NET Core.

### PR DESCRIPTION
**Pull request by kapitanov**
I've migrated QuickFIX/N to .NET Standard 1.6
Changes:

* Every project has been updated to use new csproj format
* QuickFIX now targets both NET45 and .NET Standard 1.6
* Tests were rewritten to use Xunit (since NUnit test runner barely supports .NET Core)

This PR fixes #408.
I've set an [Appveyor build](https://ci.appveyor.com/project/itgloballlc/quickfixn) for this branch. Resulting nuget package can be found [here](https://www.nuget.org/packages/QuickFix.Net.NetStandard)

### CODE REVIEW

**Comment by discosultan** [comment]
Got to love the cleaned up .csproj files! 👍 

Any particular reason to target `netstandard1.6`? I'm wondering if targeting `netstandard2.0` instead would allow to get rid of the preprocessor directives.

**Comment by kapitanov** [comment]
I needed QuickFIX for a project I'm currenly working on and tihs project targets `netstandard1.6`.
So there was no technical reason to use `netstandard1.6`.

**Comment by wklm** [comment]
So, in my opinion it would rather make sense to migrate it directly to netcore. It should be doable just by changing the version on this branch. Apart of that it seems like this deserves to be merged apart of this AppVeyor issue.

**Comment by gbirchmeier** [comment]
Has been superceded by more recent work.   (project is currently on .net core 2.0, and framework 461)

**Pull request closed without merging**
