### PR TITLE
Splitted FIX messages into projects by FIX version

### PR DESCRIPTION
**Pull request by amibar**
#158 - Reduced the quickfixn.dll footprint by moving the FIX messages to separate projects by FIX version.
#159 - Added FIX50SP1 and FIX50SP2 messages generation.
#2 - Solved

### CODE REVIEW

**Comment by huwilly** [comment]
Hello @gbirchmeier and @amibar, any news about this PR ?

**Comment by amibar** [comment]
@gbirchmeier, I rebased my PR on the latest commit. 
As you can see all tests pass.
I had to lock the nokogiri version and update the NUnit so the build will work.

Ami

**Comment by damageboy** [comment]
Hi, This resurfaced on my github notifications... I would love to see something like this go into the next version of QuickFIX/n.

I would also love to put in some effort for resolving #408 & #248 but those two are very much build/side intensive and I'd rather do them on top of this commit rather than on the current state, assuming this will go into QuickFIX/n...

Would love to hear a comment from @gbirchmeier re. where this PR stands...

Looks to me like @huwilly is also interested in this... :)

**Comment by gbirchmeier** [comment]
superceded by #476

**Pull request closed without merging**
