### PR TITLE
Adding the missing toXML functionality and QuickFIX Compatble group parsing as an option.

### PR DESCRIPTION
**Pull request by baffled**

### CODE REVIEW

**Comment by baffled** [comment]
The toXML functionality and QuickFIXCompatibleGroups are both added to make life easier for anyone migrating from the original QuickFIX. ToXML was missing, and QuickFIXCompatibleGroups allows for groups that do not have a required delimiter.

Strictly speaking, the latter violates the FIX specification but it is the way that QuickFIX works and so can be used for backward compatibility. Note that the default for this setting is False, so existing functionality will not be affected and the standard should be that group delimiters are required - whatever the dictionary says.

**Comment by vpfau** [comment]
@baffled can you please resolve conflicts and sign the contributor agreement?

**Comment by gbirchmeier** [comment]
I'm reviewing this PR.What is QuickFIXCompatibleGroup for?

**Comment by gbirchmeier** [comment]
I'm reviewing this PR.

I'm a little confused about QuickFIXCompatibleGroup.  What kind of compatibility is this trying to preserve or support?  I don't think there is a strong case for allowing invalid groups to be parsed.

**Comment by gbirchmeier** [comment]
We're keeping the ToXML part, but discarding the QuickFIXCompatibleGroup.

The former has been rebased into #585.

**Comment by baffled** [comment]
Thank you though unfortunately there are still partner systems out there that don’t adhere to your (correct) definition of group validation.

**Comment by gbirchmeier** [comment]
@baffled Can you describe what the abberant group definition is?

And when you say "Quickfix compatible", what do you mean?  Did the other QF parse it without choking?

We're not totally against special-case handling, but we need to properly understand the situation first.

**Pull request closed without merging**
