### PR TITLE
added class for web interface

### PR DESCRIPTION
**Pull request by mohit-kumar-3pillar**
there I have added a new class to enable legacy quick fix style web interface that lets you toggle various session related parameters.

### CODE REVIEW

**Comment by cbusbey** [comment]
Hi @mohit-kumar-3pillar, would you mind merging or rebasing the latest from master into your branch?  There has been a fix to the automated build in master that should help pass the build of your pr.  Thanks!

**Comment by mohit-kumar-3pillar** [comment]
Hi @cbusbey, i have merged the the latest from master into my branch. Please have a look at this.

**Comment by cbusbey** [comment]
Thanks! 🍻

**Comment by mrefky** [comment]
Hi mohit-kumar-3pillar;
Please, Is it possible to give an example of how to enable the web interface?

**Comment by mrefky** [comment]
Can anyone please advice how to enable the web interface? Thanks

**Comment by mrefky** [comment]
Ok, so this is not using the HttpAcceptPort from the configuration file;
All what was needed is to run it is as follows:

SessionSettings settings = new SessionSettings("C:\\fix\\config.cfg");
 Acceptor.HttpServer v = new HttpServer("http://127.0.0.1:8080/",settings);
                v.Start();
Thanks , this might help others I hope.

**Pull request merged**
