### PR TITLE
misspelling

### PR DESCRIPTION
**Pull request by vpfau**

### CODE REVIEW

**Comment by gbirchmeier** [comment]
Haha, nice catch.  I PR'd a release-notes update onto your branch.  Please accept that one, and then I'll merge this.

**Comment by vpfau** [comment]
> Haha, nice catch. I PR'd a release-notes update onto your branch. Please accept that one, and then I'll merge this.
Done

**Comment by gbirchmeier** [comment]
Dang, github is not updating this PR with my commit on your branch.  Laaaaame.

Guess I'll make another PR.

**Comment by gbirchmeier** [comment]
merged in #522

**Pull request closed without merging**
