### PR TITLE
#736 Don't create file logs until firm event or message 

### PR DESCRIPTION
**Pull request by nmandzyk**
#736  Postpone file creation until receiving the first message or event

### CODE REVIEW

**Comment by gbirchmeier** [comment]
What problem is this solving?

**Comment by nmandzyk** [comment]
> What problem is this solving? Is the engine writing empty files or something?

Hey Grant. Before explaining the problem let me describe in short, how our infrastructure looks like. So, we hosts our FIX server in  AKS (Azure k8s) and when we expose port to external VNET. Somebody connects to our FIX server and this imediatelly created new instance of FileLogger that created empty file in consturtor. As result we have a lot of empty files but these connection were not FIX connections just some internal k8s helthprobles. So, to avoid empty file creation, I just postpone file creation up to log the first FIX message.

**Comment by Oribow** [comment]
Hi!
Any updates on this? I am facing the exact same issue. What can we do to get this PR or something similar merged? 
Not sure how long our hdd will survive this many file creations lol.

**Comment by Oribow** [comment]
Oh I see. @gbirchmeier is doing some more comprehensive reworking of the logging at https://github.com/connamara/quickfixn/pull/830

**Comment by gbirchmeier** [comment]
I'm sorry it's still in progress.  I'm trying to make the time.

**Comment by gbirchmeier** [comment]
PR #830 will finally take care of the ClientHandlerThread logs.

**Pull request closed without merging**
