### PR TITLE
Directory.GetFiles on Linux is Case Sensitive

### PR DESCRIPTION
**Pull request by johna1203**
In linux it was not possible to find the dll.

### CODE REVIEW

**Comment by gbirchmeier** [comment]
Fixes problem originally raised by https://stackoverflow.com/questions/64765696/incorrect-beginstring-fix-4-4-in-c-sharp-quickfixn

**Comment by gbirchmeier** [comment]
Great find.  I'm hoping to find time to verify and merge some PRs later this month.

**Comment by oniony** [comment]
Is there any chance the Nuget packages could be updated with this fix?

**Comment by oniony** [comment]
Until new Nugets, you can workaround this issue with following code loaded early:

```
var assemblyLocation = Assembly.GetExecutingAssembly().Location;
var directory = Path.GetDirectoryName(assemblyLocation);

var loadedAssemblyPaths = AppDomain.CurrentDomain
                                   .GetAssemblies()
                                   .Where(a => !a.IsDynamic)
                                   .Select(a => a.Location)
                                   .Where(l => !string.IsNullOrEmpty(l))
                                   .ToHashSet();

var dllPaths = Directory.GetFileSystemEntries(directory, "QuickFix.*.dll");
foreach (var dllPath in dllPaths)
{
    if (!loadedAssemblyPaths.Contains(dllPath)) Assembly.LoadFrom(dllPath);
}
```

**Comment by gbirchmeier** [comment]
@ahossny I thought we had really killed this particular error.  Does it happen consistently when 35=8/150=F, or only sometimes?

Can you please open a new issue, paste those messages again, and also paste your config file (sensitive parts excluded)?

**Pull request merged**
